Fix test_close_circuit crash by concatenating strings
Traceback:
  File "./test/integ/control/controller.py", line 521, in test_close_circuit
    self.assertRaises(stem.InvalidArguments, controller.close_circuit, circ_id + 1024)
TypeError: cannot concatenate 'str' and 'int' objects

Also, change to standard variable name "circuit_id".

Signed-off-by: Sean Robinson <seankrobinson@gmail.com>